name: ci

on:
  push:
    branches:
      - "docker"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/javahotelbackend:latest
        
      -
        name: Restart Container
        env:
          AZURE_CLIENT_ID: 3707226f-e552-49c9-8475-7541be9199b9
          AZURE_CLIENT_SECRET: d536f622-517c-4702-b4fc-55fda18f5736
          AZURE_TENANT_ID: 98f16a07-0393-4374-8563-e33e258bcf6c
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az container restart --name yc2305hotelbackend --resource-group yc2305
          
      
          
      
    
